### ISSUE TITLE
Neither CompressFileDictionary nor CompressStreamDictionary work

### ISSUE THREAD

**Issue by chester89** [tomap/SevenZipSharp#4]
When I call one of these methods, ArgumentNullException arises.
Here's a stacktrace:
`   in System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   in System.Threading.Monitor.Enter(Object obj, Boolean& lockTaken)
   in SevenZip.ArchiveUpdateCallback.IntEventArgsHandler(Object sender, IntEventArgs e) in C:\projects\sevenzipsharp\SevenZip\ArchiveUpdateCallback.cs:line 783
   in SevenZip.InStreamWrapper.OnBytesRead(IntEventArgs e) in C:\projects\sevenzipsharp\SevenZip\StreamWrappers.cs:line 191
   in SevenZip.InStreamWrapper.Read(Byte[] data, UInt32 size) in C:\projects\sevenzipsharp\SevenZip\StreamWrappers.cs:line 174`

**Comment by chester89** [comment]
Unfortunately, this problem prevents me from saving in-memory streams directly to archive without hitting disk, which in my case is a big problem.
I cloned the repository and tried running corresponding lines from SevenZipTests project, but it won't load the 7z.dll for some reason.
I use VS2013 with .NET 4.5 on Windows 7.
Can you help @tomap?

**Comment by chester89** [comment]
native libary loading is solved, and I've found the bug with those methods. Pull request should be out next week

**Comment by yashbajra** [comment]
#10

**Comment by yashbajra** [comment]
#10

**Comment by chester89** [comment]
Closed via #5. Thanks @tomap @yashbajra !
